# Generated by Django 5.1.5 on 2025-02-13 13:20

from django.db import migrations, models


from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    CustomUser = apps.get_model('task_App', 'CustomUser', 'CustomUserManager')

    if not CustomUser.objects.filter(email='admin@tt.com').exists():
        admin_user = CustomUser.objects.create(
        username='admin',
        email='admin@tt.com',
        password=make_password('admin123'),  # Use make_password to hash the password
        role = 'admin',
        is_staff=True,
        is_superuser=True
    )
        
        admin_user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('task_App', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),

        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_status',
            field=models.CharField(choices=[('testing', 'Testing'), ('working', 'Working'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
